
import { CompanyCategory } from './companyTypes';

// Enhanced pre-defined company category mappings (similar to financial aggregators data)
const COMPANY_MAPPINGS: Record<string, CompanyCategory> = {
  // Top Tier - Category A (MNCs, Large Listed Companies)
  "tata": "A",
  "infosys": "A",
  "wipro": "A",
  "tcs": "A",
  "reliance": "A",
  "hdfc": "A",
  "google": "A", 
  "microsoft": "A",
  "amazon": "A",
  "apple": "A",
  "meta": "A",
  "facebook": "A",
  "ibm": "A",
  "accenture": "A",
  "mahindra": "A",
  "cisco": "A",
  "intel": "A",
  "oracle": "A",
  "icici": "A",
  "sbi": "A",
  "axis bank": "A",
  "pwc": "A",
  "deloitte": "A",
  "kpmg": "A",
  "ey": "A",
  "l&t": "A",
  "nestle": "A",
  "unilever": "A",
  "hindustan unilever": "A",
  "hul": "A",
  "hp": "A",
  "dell": "A",
  "adobe": "A",
  "airtel": "A",
  "bharti": "A",
  "jio": "A",
  "netflix": "A",
  "walmart": "A",
  "nike": "A",
  "samsung": "A",
  "sony": "A",
  "toyota": "A",
  "honda": "A",
  "adani group": "A",
  "hindustan petroleum": "A",
  "indian oil": "A",
  "coal india": "A",
  "ntpc": "A",
  "power grid": "A",
  "bhel": "A",
  "gail": "A",
  "maruti suzuki": "A",
  "hero motocorp": "A",
  "hdfc bank": "A",
  "kotak bank": "A",
  "idfc bank": "A",
  "indusind bank": "A",
  "federal bank": "A",
  "hexaware": "A",
  
  // Mid Tier - Category B
  "mindtree": "B",
  "cognizant": "B",
  "capgemini": "B",
  "tech mahindra": "B",
  "hcl": "B",
  "ltimindtree": "B",
  "larsen & toubro": "B",
  "adani": "B",
  "birla": "B",
  "aditya birla": "B",
  "kotak": "B",
  "yes bank": "B",
  "bajaj": "B",
  "cipla": "B",
  "zomato": "B",
  "swiggy": "B",
  "paytm": "B",
  "ola": "B",
  "byjus": "B",
  "oyo": "B",
  "flipkart": "B",
  "myntra": "B",
  "makemytrip": "B",
  "cleartrip": "B",
  "yatra": "B",
  "irctc": "B",
  "adp": "B",
  "genpact": "B",
  "mphasis": "B",
  "persistent": "B",
  "cyient": "B",
  "cgi": "B",
  "tata power": "B",
  "tata steel": "B",
  "suzlon": "B",
  "godrej": "B",
  "jubilant": "B",
  "lupin": "B",
  "sun pharma": "B",
  "dr reddy": "B",
  "apollo hospitals": "B",
  "fortis": "B",
  "max healthcare": "B",
  "policybazaar": "B",
  "paisabazaar": "B",
  "bankbazaar": "B",
  "justdial": "B",
  "naukri": "B",
  "infoedge": "B",
  "eicher motors": "B",
  "tvs motors": "B",
  "ashok leyland": "B",
  
  // Regular - Category C
  "state government": "C",
  "central government": "C",
  "government": "C",
  "railways": "C",
  "postal": "C",
  "education department": "C",
  "health department": "C",
  "municipality": "C",
  "panchayat": "C",
  "public works": "C",
  "public sector": "C",
  "bsnl": "C",
  "sail": "C",
  "ongc": "C",
  "bank of india": "C",
  "bank of baroda": "C",
  "canara bank": "C",
  "corporation bank": "C",
  "punjab national bank": "C",
  "union bank": "C",
  "indian bank": "C",
  "allahabad bank": "C",
  "andhra bank": "C",
  "central bank": "C",
  "syndicate bank": "C",
  "ucb bank": "C",
  "indian overseas bank": "C",
  "dena bank": "C",
  "vijaya bank": "C",
  "oriental bank": "C",
  "army": "C",
  "navy": "C",
  "air force": "C",
  "defence": "C",
  "police": "C",
  "healthcare department": "C",
  "university": "C",
  "college": "C",
  "school": "C",
  "teaching": "C",
  "nursing": "C",
  "psu": "C",
  "public sector undertaking": "C",
  "electricity board": "C",
  "water board": "C",
  "transport corporation": "C",
  "municipal corporation": "C",
  "zilla parishad": "C",
  "grameen bank": "C",
  
  // Small Business/Self-employed - Category D
  "self employed": "D",
  "freelancer": "D",
  "consultant": "D",
  "proprietor": "D",
  "startup": "D",
  "small business": "D",
  "shop": "D",
  "retail": "D",
  "local business": "D",
  "partnership firm": "D",
  "micro enterprise": "D",
  "kirana": "D",
  "restaurant": "D",
  "cafe": "D",
  "bakery": "D",
  "salon": "D",
  "boutique": "D",
  "tailor": "D",
  "carpenter": "D",
  "plumber": "D",
  "electrician": "D",
  "mechanic": "D",
  "driver": "D",
  "taxi": "D",
  "private practice": "D",
  "clinic": "D",
  "pharmacy": "D",
  "medical store": "D",
  "general store": "D",
  "provision store": "D",
  "stationery shop": "D",
  "hardware store": "D",
  "food stall": "D",
  "coaching center": "D",
  "tuition center": "D",
  "gym": "D",
  "fitness center": "D",
  "yoga center": "D",
  "property dealer": "D",
  "broker": "D",
  "travel agent": "D",
  "event manager": "D",
  "wedding planner": "D",
  "content creator": "D",
  "youtuber": "D",
  "influencer": "D"
};

export default COMPANY_MAPPINGS;
